lcp/mokutil

configure.ac, src/mokutil.c
This source tree uses:
typedef wchar_t efi_char16_t;
to define UEFI's UCS-2 character type.  On many platforms, wchar_t is
32-bits by default.  As a result, efichar_from_char winds up writing
4-byte characters instead of 2-byte characters.  In the case where we
hash the password in mokutil, this works fine, because the same datatype
is used, and the values are the same.  But for our feature toggles,
where we store the raw data and shim is interpretting the character
array, every other character winds up being L'\0', and verification
fails.
So always build with -fshort-wchar to ensure we get 2-byte character
storage.
Signed-off-by: Peter Jones <pjones@redhat.com>
=> Build with -fshort-wchar so toggle passwords work right.

src/mokutil.c
The code to make file modes implicit in efivar was *really* not working well with gcc 6, and probably was not working right in gcc 5, so efivar 0.23 requires explicitly setting the mode in efi_set_variable().  This patch makes it all explicitly set to a reasonable value.
Signed-off-by: Peter Jones <pjones@redhat.com>
=> mokutil: be explicit about file modes in all cases.

src/mokutil.c
Signed-off-by: Tyler Hicks <tyhicks@canonical.com>
=> Fix typo in error message when the system lacks Secure Boot support

src/mokutil.c
Signed-off-by: Peter Jones <pjones@redhat.com>
=> list_keys_in_var(): check errno correctly, not ret twice.

src/mokutil.c
Fixes:
error: taking address of packed member of ‘struct <anonymous>’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
=> Avoid taking pointer to packed struct

src/mokutil.c
Other function integers are unsigned but size_t looks better fit
Closes #28
=> Fix 32-bit build

src/mokutil.c
This fixes a few -Wcast-algin warnings emitted by clang. e.g
mokutil.c:1866:26: error: cast from 'uint8_t *' (aka 'unsigned char *') to 'uint32_t *' (aka 'unsigned int *') increases required alignment
from 1 to 4 [-Werror,-Wcast-align]
secureboot = (int32_t)*(uint32_t *)data;
^~~~~~~~~~~~~~~~
Casting from uint8_t* to uint32_t* is undefined behavior and can also lead to
bugs on platforms that require pointers to be aligned to the load size.
I think I was able to duplicate the existing logic, but I was unsure how to test this.
=> Fix -Wcast-align warnings

src/mokutil.c
Mokutil always check whether the machine supports Secure Boot or not and
it exits with an error message if Secure Boot is not supported. But some
options don't need it to be supported and could be used regardless.
For example, shim could be installed on machines where SB is not enabled
or supported. Options such as set-verbosity could be useful in this case
even without Secure Boot.
Signed-off-by: Javier Martinez Canillas <javierm@redhat.com>
=> mokutil: only check for Secure Boot in options that need it

man/mokutil.1, src/mokutil.c
This variable contains the descriptive form of all the components used by
the operating systems that ship signed shim binaries. Along with a minimum
generation number for each component. More information in can be found in
the UEFI Secure Boot Advanced Targeting (SBAT) specification:
https://github.com/rhboot/shim/blob/main/SBAT.md
Since a SBAT variable contains a set of Comma Separated Values (CSV) UTF-8
encoded strings, the data could just be printed without the need to do any
previous processing.
Signed-off-by: Javier Martinez Canillas <javierm@redhat.com>
=> mokutil: Add option to print the UEFI SBAT variable content

src/mokutil.c, src/util.c, src/util.h
This patch adds support for getting mok variables from
/sys/firmware/efi/mok-variables/$NAME , if they are present, as well as
for checking MokListRT, MokListRT1, MokListRT2, etc., for any of the mok
variables.
Signed-off-by: Peter Jones <pjones@redhat.com>
=> mokutil: add mok-variables parsing support

src/mokutil.c
The SBAT data was previously in an EFI variable called "SBAT" but this
got renamed to "SbatLevelRT" in the following shim commit:
https://github.com/rhboot/shim/commit/27da4170f0f
Read the new variable instead of the old one that is not used anymore.
Signed-off-by: Javier Martinez Canillas <javierm@redhat.com>
=> mokutil: Read the SbatLevelRT variable to get the SBAT content

src/util.c
Instead of setting the passed data_sizeop to NULL pointer, only reset the value it points to.
=> src/util.c: fix NULL pointer dereference in mok_get_variable

src/efi_x509.c
Commit a2bffce159d ("efi_x509: convert the cert to X509 directly") stopped
using a BIO buffer and instead just created a X509 object directly.
Unfortunately that change also broke the certs fingerprint calculation due
a behaviour of the d2i_X509() function that's not intuitive at all.
The function modifies the value of the pointer passed as second argument,
which points to the certificate data. This causes the SHA1 digests to be
calculated against the wrong buffers and leads to invalid fingerprints:
Before the mentioned commit:
```
./src/mokutil --db | grep -i fingerprint
SHA1 Fingerprint: 7b:9e:6c:c3:c2:2e:2a:f2:4f:5b:eb:27:d5:df:f7:3d:5d:74:e1:66
SHA1 Fingerprint: cb:02:59:71:48:26:c8:67:d1:42:2c:31:0b:88:15:01:60:39:8f:0b
SHA1 Fingerprint: …
```
=> efi_x509: fix certificates fingerprint calculation

data/mokutil, man/mokutil.1, src/mokutil.c
Having `mokutil` handle **FALLBACK_VERBOSE** and **FB_NO_REBOOT** variables eases fallback debugging.
=> mokutil: enable setting fallback verbosity and noreboot mode

man/mokutil.1, src/mokutil.c
Control how shim will apply SBAT revocations:
mokutil --set-sbat-policy latest
applies the latest SBAT revocations
(default behavior)
mokutil --set-sbat-policy previous
applies previous SBAT revocations to
allow falling back to an older release
In both of the above cases shim will only apply SBAT revocations that
are newer than the ones currently installed.
mokutil --set-sbat-policy delete
resets SBAT revocations only if Secure
Boot is disabled. This setting does not
persist.
Signed-off-by: Jan Setje-Eilers <Jan.SetjeEilers@oracle.com>
=> SBAT revocation update support

src/mokutil.c
The -s option can cause unexcepted result.
Signed-off-by: gaoyusong <gaoyusong2@huawei.com>
=> mokutil bugfix: del unused opt "-s"

configure.ac
Do not hardcode the pkg-config command to support compiling on cross
where e.g. the pkg-config command may be prefixed by the host triplet
x86_64-pc-linux-gnu-pkg-config.
See also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=884798
=> Use PKG_PROG_PKG_CONFIG macro from pkg.m4 to detect pkg-config

src/mokutil.c
All messages in `print_skip_message()` but one mention "original" efi vars (like MokList) instead of their runtime copies (like MokListRT). This pr makes it consistent.
=> Fix inconsistency in skip messages

src/mokutil.h
It's not necessary to define 'efi_char16_t' as 'wchar_t' since we don't need any wchar functions. Besides, it may conflict with efivar-38. This commit defines 'efi_char16_t' as 'uint16_t' and adds the conditional check to avoid the potential conflict.
Fixes: https://github.com/lcp/mokutil/issues/66
=> Avoid conflicting efi_char16_t type definitions

src/mokutil.c
- Don't return with non zero status for version query
- Check for efi variables support post processing of command line args.
=> Misc fixes

src/mokutil.c
One of our static checkers noticed the following:
```
Error: OVERRUN (CWE-119):
mokutil-0.6.0/src/mokutil.c:378: cond_at_least: Checking ""read_len < 300L"" implies that ""read_len"" is at least 300 on the false branch.
mokutil-0.6.0/src/mokutil.c:394: overrun-local: Overrunning array ""string"" of 300 bytes at byte offset 300 using index ""read_len"" (which evaluates to 300).
```
This is because the read loop limits itself to < BUF_SIZE, but the actual read() call uses BUF_SIZE - read_len as the size, and then updates read_len with the added number of characters:
```
while (read_len < BUF_SIZE) {
ssize_t rc = read (fd, string + read_len,
BUF_SIZE - read_len - 1);
...
read_len += rc;
}
```
This means it's asking for BUF_SIZE characters, and as a result read_len can be adjusted to be …
=> Fix an off-by-one reading passwords from a file.

src/mokutil.c
Since the verbose form is already used for years, changing the default behavior may affect the scripts in use. This commit reverts the default listing method to 'verbose', drops '--verbose-listing', and adds '--short'.
=> mokutil: revert the default listing to the verbose form

src/password-crypt.c, src/password-crypt.h
static const char b64t[64] triggers compiler warning which in turn makes the build fail with
-Werror=unterminated-string-initialization, so removing this string with the the unused int_to_b64() function which is the only function using this array.
=> mokutil: remove unused int_to_b64()
